name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Convert JUnit XML to CTRF
      run: npx junit-to-ctrf "app/etc/Failed.xml" -o app/etc/Failed.json

    - name: Check for file using bash
      shell: bash
      run: |
        FILE="app/etc/Failed.json"
        if [ -f "$FILE" ]; then
          echo "$FILE exists."
        else
          echo "$FILE not found."
          exit 1 
        fi
    

    - name: Publish Passed Test Report
      uses: ctrf-io/github-test-reporter@v1
      if: always()
      with:
        report-path: 'app/etc/Failed.json'
        github-report: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Passed test results
      uses: ctrf-io/github-test-reporter@v1
      with:
        report-path: 'app/etc/Failed.json'
        upload-artifact: true
      if: always()

#    - name: Publish Failed Test Report
#      uses: ctrf-io/github-test-reporter@v1
#      if: always()
#      with:
#        report-path: 'app/etc/Failed.xml'
#        github-report: true
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#    - name: Upload Failed test results
#      uses: ctrf-io/github-test-reporter@v1
#      with:
#        report-path: 'app/etc/Failed.xml'
#        upload-artifact: true
#      if: always()

#    - name: Publish Test Report
#      uses: ctrf-io/github-test-reporter@v1
#      with:
#        report-path: 'app/etc/*.json'
#        pull-request-report: true
#        summary-report: true
#        failed-report: true
#        flaky-report: true
#        insights-report: true
#        test-report: true
#        # Order reports with the most important information first
#        report-order: 'summary-report,failed-report,flaky-report,insights-report,test-report'
#
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      if: always()
#
#    - name: Upload test results
#      uses: ctrf-io/github-test-reporter@v1
#      with:
#        report-path: 'app/etc/*.json'
#        upload-artifact: true
#      if: always()
