name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Convert Passed JUnit XML file to CTRF JSON Format
      run: npx junit-to-ctrf "app/etc/Passed.xml" -o app/etc/Passed.json

    - name: Check if Passed File contains using bash
      id: file-exists
      shell: bash
      run: |
        FILE="app/etc/Passed.json"
        if [ -f "$FILE" ]; then
          echo "$FILE exists."
          exit 0
        else
          echo "$FILE not found."
          exit 1 
        fi

#    - name: Publish Passed Test Report
#      uses: ctrf-io/github-test-reporter@v1
#      if: ${{ steps.file-exists.outcome == 'success' }}
#      with:
#        report-path: 'app/etc/Passed.json'
#        github-report: true
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Passed test results
      uses: ctrf-io/github-test-reporter@v1
      if: ${{ steps.file-exists.outcome == 'success' }}
      with:
        report-path: 'app/etc/Passed.json'
        upload-artifact: true
