name: Android CI

on:
  push:
    branches: [ "mytest" ]
  pull_request:
    branches: [ "mytest" ]

jobs:
  BuildUnitTest:
    runs-on: ubuntu-latest

    permissions:
      actions: read 
      contents: read

    steps:

    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Convert Test JUnit XML file to CTRF JSON Format
      run: npx junit-to-ctrf "app/etc/test.xml" -o app/etc/test.json

    - name: Check if Test File contains using bash
      id: file-exists
      shell: bash
      run: |
        FILE="app/etc/test.json"
        if [ -f "$FILE" ]; then
          echo "$FILE exists."
          exit 0
        else
          echo "$FILE not found."
          exit 1 
        fi

    - name: Publish Test Report with Insights
      uses: asadmansr/android-test-report-action@v1.2.0
      with:
        args: 'app/etc/test.json'
      if: always()
